version: '3'

services:
  app:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
      # Inherited from .env file
      args:
        - UID=$UID
        - GID=$GID
    # Use docker init process to speedup
    # container closing on hang processes
    init: true
    volumes:
      # Forward current directory into docker container.
      # We forward it into workspace, so our project directory won't be cluttered
      # by ~ (HOME) .dotfiles
      - .:/home/vscode/workspace
